#!/usr/bin/env bash
set -e

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  >&2 echo "Usage: $(basename $0) <author> [commit]"
  exit 1
fi

AUTHOR=${1:?}
if [ "$1" = "random" ]; then
    AUTHOR=$(git log --all --format='%aN <%cE>' | sort -u | shuf | head -n 1)
fi
AUTHOR_NAME=$(echo $AUTHOR | perl -wlne '/^([^<]+).*>$/ and print $1')
AUTHOR_EMAIL=$(echo $AUTHOR | perl -wlne '/^.*\s*<(.*)>$/ and print $1')
COMMIT=$(git rev-parse --short ${2:-HEAD})

{
  git stash push -a -m "__git-blame-someone-else"
  GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT/edit $COMMIT/'" git rebase -i $COMMIT~1^^
  GIT_COMMITTER_NAME="$AUTHOR_NAME" GIT_COMMITTER_EMAIL="$AUTHOR_EMAIL" git commit --amend --no-edit --author="$AUTHOR" --allow-empty
  git rebase --continue
  git stash list | grep "__git-blame-someone-else" && git stash pop
} &> /dev/null

INSULTS=(
	"You're officially an asshole."
	"Great job."
	"You dirty animal."
	"They owe you one."
	"They'll never live this down."
)

INDEX=$(($RANDOM % ${#INSULTS[@]}))

echo "$AUTHOR_NAME is now the author of $COMMIT. ${INSULTS[$INDEX]}";
